Fix 2016 term start date
everypolitician-scrapers/australia-openaustralia-senators pull request #2
Opened 2016-09-22 10:06 UTC by ondenman

The date and the month of the start of the 45th term were in the wrong order.

2016-09-22 14:44 UTC, tmtmtmtm requested changes
I think this needs to credit a source in the commit message.

NB: Is the end date for the 44th term correct (and thus different from the House of Representatives), or is it also wrong here?

2016-09-22 14:48 UTC, ondenman commented
Amended commit message.

2016-09-23 07:57 UTC, tmtmtmtm approved these changes

2016-09-23 07:58 UTC, tmtmtmtm commented
We probably also want to switch this to pull these in from EveryPolitician, similar to the Representatives, but let's get the flow correct in this direction first.

2016-09-23 07:58 UTC, merged